from __future__ import annotations

from typing import Any, Protocol, Sequence

from .models import Capture, ChangeEvent, Detection, DroneTelemetry, MappingArtifact, Mission, Segmentation, Track


class PhotogrammetryProvider(Protocol):
    def process_capture(self, capture: Capture, image_uris: Sequence[str]) -> str: ...
    def get_status(self, provider_job_id: str) -> dict[str, Any]: ...
    def get_artifacts(self, provider_job_id: str, capture: Capture) -> list[MappingArtifact]: ...


class DetectorProvider(Protocol):
    def detect_image(self, artifact: MappingArtifact) -> list[Detection]: ...
    def detect_tiles(self, artifacts: Sequence[MappingArtifact]) -> list[Detection]: ...
    def detect_batch(self, artifacts: Sequence[MappingArtifact]) -> list[list[Detection]]: ...


class SegmentationProvider(Protocol):
    def segment_image(self, artifact: MappingArtifact) -> list[Segmentation]: ...
    def segment_tiles(self, artifacts: Sequence[MappingArtifact]) -> list[Segmentation]: ...


class ChangeDetectionProvider(Protocol):
    def compare(self, before: Capture, after: Capture) -> list[ChangeEvent]: ...


class TrackingProvider(Protocol):
    def associate_detections(self, detections: Sequence[Detection]) -> dict[str, list[Detection]]: ...
    def build_tracks(self, site_id: str, groups: dict[str, list[Detection]]) -> list[Track]: ...


class DroneProvider(Protocol):
    async def connect(self) -> dict[str, Any]: ...
    async def get_telemetry(self) -> DroneTelemetry: ...
    async def upload_mission(self, mission: Mission) -> None: ...
    async def start_mission(self) -> None: ...
    async def return_to_launch(self) -> None: ...
